version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  beta:
    machine: true
    resource_class: tadashi0713/ec2-mac
    steps:
      - run: echo 'eval "$(rbenv init - bash)"' >> $BASH_ENV
      - checkout
      - run: bundle install
      - run: bundle exec fastlane beta

workflows:
  main:
    jobs:
      - beta:
          context: # Context
            - mobile
