version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
  macos: circleci/macos@2.1.0

jobs:
  unit_test_medium:
    macos:
      xcode: 13.2.1
    # Resource class
    resource_class: medium
    steps:
      - checkout
      # Ruby Orb(Install fastlane)
      - ruby/install-deps
      - run: bundle exec fastlane unit_test
      # Store Test Results
      - store_test_results:
          path: fastlane/test_output/report.junit

  unit_test_large:
    macos:
      xcode: 13.2.1
    # Resource class
    resource_class: large
    steps:
      - checkout
      # Ruby Orb(Install fastlane)
      - ruby/install-deps
      - run: bundle exec fastlane unit_test
      # Store Test Results
      - store_test_results:
          path: fastlane/test_output/report.junit

  unit_test_ec2_mac_runner:
    machine: true
    resource_class: tadashi0713/ec2-mac
    steps:
      - checkout
      - ruby/install-deps:
          key: ec2-mac-runner
      - run: bundle exec fastlane unit_test

  # ui_test:
  #   macos:
  #     xcode: 13.1.0
  #   resource_class: large
  #   steps:
  #     - checkout
  #     # Preboot iOS Simulator
  #     - macos/preboot-simulator:
  #         device: iPhone 13
  #         version: "15.0"
  #     - ruby/install-deps
  #     - run: bundle exec fastlane ui_test
  #     - store_test_results:
  #         path: fastlane/test_output/report.junit

  # beta:
  #   macos:
  #     xcode: 13.1.0
  #   resource_class: large
  #   steps:
  #     - checkout
  #     - ruby/install-deps
  #     - run: bundle exec fastlane beta

workflows:
  main:
    jobs:
      - unit_test_medium
      - unit_test_large
      - unit_test_ec2_mac_runner
