version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  beta:
    machine: true
    resource_class: tadashi0713/ec2-mac
    steps:
      - checkout
      - run: | 
          source ~/.zshrc
          ruby --version
          bundle install
      # - ruby/install-deps:
      #     key: ec2-mac-runner
      - run: bundle exec fastlane beta

workflows:
  main:
    jobs:
      - beta:
          context: # Context
            - mobile
