version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
  macos: circleci/macos@2.1.0

jobs:
  beta:
    machine: true
    resource_class: tadashi0713/ec2-mac
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec fastlane beta

workflows:
  main:
    jobs:
      - beta:
          context: # Context
            - mobile
